apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:${POSTGRES_PORT}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    database: ${POSTGRES_DB}
    isDefault: true
    jsonData: 
      sslmode: "disable"
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      postgresVersion: 1500
    version: 1
    editable: False