version: 2 

models: 
  - name: artist_and_genre_preferences
    description: "Aggregates artist popularity trends over time, user-specific affinity."
  
  - name: playlist_composition_metrics
    description: "Aggregates metrics on playlist composition, including genre diversity and artist variety."
  
  - name: user_listening_behavior
    description: "Aggregates user listening patterns, including time of day, day of week, genre preferences, track diversity and artist exploration."

  