name: 'spotify_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'spotify_dbt'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "logs"

# Configuring models
models:
  spotify_dbt:
    # Config indicated by + and applies to all files under models/
    +materialized: view

    staging:
      +materialized: view
      
    marts:      
      analytical:
        +materialized: table
        
      reporting:
        +materialized: table
        listening_activity_report:
          +materialized: view

    # utils:
    #   +materialized: view

# Macros configuration
macros:
  spotify_dbt:
    calculate_affinity_scores:
      +description: "Calculates affinity scores between users and content"
    generate_audio_feature_segments:
      +description: "Generates segments based on audio features"

