spotify_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      port: "{{ env_var('SPOTIFY_DB_PORT') | int }}"
      user: "{{ env_var('SPOTIFY_DB_USER') }}"
      password: "{{ env_var('SPOTIFY_DB_PASSWORD') }}"
      dbname: "{{ env_var('SPOTIFY_DB') }}"
      schema: public
      threads: 4
      keepalives_idle: 0
    
    prod:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      port: "{{ env_var('SPOTIFY_DB_PORT') | int }}"
      user: "{{ env_var('SPOTIFY_DB_USER') }}"
      password: "{{ env_var('SPOTIFY_DB_PASSWORD') }}"
      dbname: "{{ env_var('SPOTIFY_DB') }}"
      schema: public
      threads: 8
      keepalives_idle: 0