spotify_dbt:
  target: dev
  outputs:
    dev:
      host: localhost
      dbname: "{{ env_var('POSTGRES_DB') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: "{{ env_var('POSTGRES_PORT') | int }}"
      schema: public
      threads: 4
      type: postgres
